import os

LOG_FILE_PATH               = os.path.join(os.getcwd(), "log.log")
DEVICE_IDS_PATH             = os.path.join(os.getcwd(), "src", "temp", "devices.txt")
DATABASE_PATH               = os.path.join(os.getcwd(), "src", "temp", "database.db")
MANAGEMENT_CHOICE_VIEW_PATH = os.path.join(os.getcwd(), "src", "view", "management_choice.txt")
SINGLE_MANAGEMENT_VIEW_PATH = os.path.join(os.getcwd(), "src", "view", "single_management.txt")
BOT_MANAGEMENT_VIEW_PATH    = os.path.join(os.getcwd(), "src", "view", "bot_management.txt")
CHAT_MODERATION_VIEW_PATH   = os.path.join(os.getcwd(), "src", "view", "chat_moderation.txt")
BADASS_VIEW_PATH            = os.path.join(os.getcwd(), "src", "view", "badass.txt")
LOGO_VIEW_PATH              = os.path.join(os.getcwd(), "src", "view", "logo.txt")
ICONS_PATH                  = os.path.join(os.getcwd(), "src", "icons")
CHAT_SETTINGS_PATH          = os.path.join(os.getcwd(), "src", "chat_settings")
ACCOUNTS_DIR_PATH           = os.path.join(os.getcwd(), "src", "accounts")
REG_DEVICES_PATH            = os.path.join(os.getcwd(), "src", "accounts", "reg_devices.txt")
CREATED_ACCOUNTS_PATH       = os.path.join(os.getcwd(), "src", "accounts", "created_accounts.txt")
BOTS_TXT_PATH               = os.path.join(os.getcwd(), "src", "bots.txt")
